{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "7.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.3.0.aar",
          "url": "viewbinding-7.3.0.aar",
          "size": 2228,
          "sha512": "dc449fa1cd6ca0f3f8657f250abe38fd59a260cc639eee9b693ab19ab633ba267f5db6794621f6445ab1a7485bf15c3994bcd3d87369d8f9737e975f44a589e8",
          "sha256": "9bdd5f2a025ec1f5d4e4352d80836621c057d632a2e17306142f773e251c3a53",
          "sha1": "b50ec9f629303b2ba9e9438f3445ea687f6e0604",
          "md5": "6652a486c901151078d6a1cfe4a8de23"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.3.0.aar",
          "url": "viewbinding-7.3.0.aar",
          "size": 2228,
          "sha512": "dc449fa1cd6ca0f3f8657f250abe38fd59a260cc639eee9b693ab19ab633ba267f5db6794621f6445ab1a7485bf15c3994bcd3d87369d8f9737e975f44a589e8",
          "sha256": "9bdd5f2a025ec1f5d4e4352d80836621c057d632a2e17306142f773e251c3a53",
          "sha1": "b50ec9f629303b2ba9e9438f3445ea687f6e0604",
          "md5": "6652a486c901151078d6a1cfe4a8de23"
        }
      ]
    }
  ]
}
